name: Complete Workflow

on: [push, pull_request]

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
  FORCE_COLOR: "1"

jobs:
  pre-commit-check:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    uses: ./.github/workflows/pre-commit-check.yml
    secrets: inherit
  run-tests-cpu:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    uses: ./.github/workflows/run-tests-cpu.yml
    secrets: inherit
  run-tests-gpu:
      if: |
        github.ref == 'refs/heads/main' ||
        startsWith(github.ref, 'refs/tags/') ||
        contains(github.event.head_commit.message, '[gpu]')
      uses: ./.github/workflows/run-tests-gpu.yml
      secrets: inherit